asynchronously return the tidied tree
michael-ciniawsky/posthtml-tidy pull request #2
Opened 2017-02-09 04:14 UTC by morewry

I noticed that htmltidy options that typically result in changes to the markup, such as dropping empty tags, weren't reflected in output files. To all appearances, if the `log` option is not set to true, posthtml-tidy doesn't do anything.

This is because the input tree is passed immediately out again without any changes. This pull request parses htmltidy's output back into a tree and returns that tree instead (as a Promise resolution).

2017-02-09 05:32 UTC, Scrum requested changes

2017-02-09 05:32 UTC, GitScrum commented on index.js
> +};
so it seems to me more elegant.
```js
const log = function (err, msg) {
    if (err) {
      console.log(chalk.red(err))
    }
    console.log(chalk.green(msg))
}
```

2017-02-09 05:32 UTC, GitScrum commented on index.js
> +          reject(err || 'Unknown problem in posthtml-tidy.')
so it seems to me more elegant.
```js
if (options.log) {		 
  log(err, msg)
}

if (err) {
  reject(err || 'Unknown problem in posthtml-tidy.')
}

resolve(parser(msg))
```

2017-02-09 06:10 UTC, michael-ciniawsky requested changes
@see suggestions by @GitScrum. This module definitely needs some love and is a long outstanding TODO on my list, give me a few hours after merging this PR to add tests etc... :) thx in advance @morewry

2017-02-09 06:10 UTC, michael-ciniawsky commented on index.js
> +};
yep

2017-02-09 06:10 UTC, michael-ciniawsky commented on index.js
> +          reject(err || 'Unknown problem in posthtml-tidy.')
yep

2017-02-09 18:56 UTC, morewry commented
Agreed on those changes. I'll update.

2017-02-10 07:13 UTC, morewry commented
FWIW, it's possible to have both `err` and `msg` if you are, for example, using the `accessibility-check` option.

2017-02-10 17:41 UTC, michael-ciniawsky commented
@morewry Thx

2017-02-10 17:41 UTC, merged